spring:
  data:
    mongodb:
      username: ala
      password: ala
      host: localhost
      database: notification
      authentication-database: admin
      port: 27017
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup.OrderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ala.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.ala.ecommerce.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: ala
    password: ala
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000