spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: ala
    password: ala
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ala
    password: ala
    baseline-description: "init"
    baseline-version: 0
server:
  port: 8050